spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - AuthFilter


        - id: customer-service
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/api/v1/customers/**
          filters:
            - AuthFilter



        - id: order-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - AuthFilter

        - id: order-lines-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order-lines/**
          filters:
            - AuthFilter

        - id: product-service
          uri: lb:http://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
          filters:
            - AuthFilter


        - id: product-images
          uri: lb:http://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/images/**
          filters:
            - RewritePath=/api/v1/images/(?<path>.*), /api/v1/images/${path}

        - id: payment-service
          uri: lb:http://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - AuthFilter
server:
  port: 8555

