version: "3.9"

services:
  # -------------------------------------------------------------------
  # 1) INFRASTRUCTURE (identique à ton fichier d’origine)
  # -------------------------------------------------------------------
  postgres:
    container_name: ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: ayoub
      POSTGRES_PASSWORD: ayoub
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks: [microservices-net]
    restart: unless-stopped

  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks: [microservices-net]
    restart: unless-stopped

  mongodb:
    container_name: ms_mongo_db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ayoub
      MONGO_INITDB_ROOT_PASSWORD: ayoub
    volumes:
      - mongo:/data
    ports:
      - 27017:27017
    networks: [microservices-net]

  mongo-express:
    container_name: ms_mongo_express
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ayoub
      ME_CONFIG_MONGODB_ADMINPASSWORD: ayoub
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - 8081:8081
    networks: [microservices-net]
    restart: unless-stopped

  mail-dev:
    container_name: ms_mail_dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks: [microservices-net]

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks: [microservices-net]

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: ms_kafka
    depends_on: [zookeeper]
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    ports:
      - 9092:9092
    networks: [microservices-net]

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks: [microservices-net]

  keycloak:
    container_name: keycloak-ms
    image: quay.io/keycloak/keycloak
    command: ["start-dev"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 9098:8080
    networks: [microservices-net]

  # -------------------------------------------------------------------
  # 2) MICRO-SERVICES SPRING BOOT
  #    (compilés dans /services/<name>/target/…)
  # -------------------------------------------------------------------
  config-server:
    build: ./services/config-server            # Dockerfile déjà présent
    container_name: ms_config
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 8888:8888
    networks: [microservices-net]
    depends_on: [postgres]

  discovery-service:
    build: ./services/discovery
    container_name: ms_discovery
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 8761:8761
    networks: [microservices-net]
    depends_on: [config-server]

  gateway-service:
    build: ./services/gateway
    container_name: ms_gateway
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 8080:8080
    networks: [microservices-net]
    depends_on: [config-server, discovery-service]

  product-service:
    build: ./services/product
    container_name: ms_product
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 9001:9001
    networks: [microservices-net]
    depends_on: [postgres, config-server, discovery-service]

  customer-service:        # ← ex-« user » / « customer » selon ton code
    build: ./services/customer
    container_name: ms_customer
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 9002:9002
    networks: [microservices-net]
    depends_on: [postgres, config-server, discovery-service, keycloak]

  order-service:
    build: ./services/order
    container_name: ms_order
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 9003:9003
    networks: [microservices-net]
    depends_on: [postgres, kafka, config-server, discovery-service]

  payment-service:
    build: ./services/payment
    container_name: ms_payment
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 9004:9004
    networks: [microservices-net]
    depends_on: [postgres, config-server, discovery-service]

  notification-service:
    build: ./services/notification
    container_name: ms_notification
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 9005:9005
    networks: [microservices-net]
    depends_on: [kafka, config-server, discovery-service]

# -------------------------------------------------------------------
# RÉSEAUX & VOLUMES
# -------------------------------------------------------------------
networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo:
